### ISSUE TITLE
 The link to the dataset.

### ISSUE THREAD

**Issue by Anywayany** [matciotola/hyperspectral_pansharpening_toolbox#1]
Deer Dr. Ciotola,

Thanks for your hyperspectral pansharpening toolbox, this is great work, which will benefit the remote sensing society a lot. However, I have a question about where the dataset link is. 

Best wishes.

**Comment by matciotola** [comment]
We are working on it. Maybe in the next two weeks, everything will be released and detailed. Sorry for being late!

**Comment by matciotola** [comment]
@Anywayany, infos about the dataset are now provided. Please, report any problems/errors/improvements to me.
Thank you,
Matteo
