### ISSUE TITLE
Size mismatch during RR evaluation

### ISSUE THREAD

**Issue by shwangtangjun** [matciotola/hyperspectral_pansharpening_toolbox#2]
Thanks for your nice benchmark. Everything works fine for FR experiments. However, when I try to do RR experiments, size mismatch error occurs when I test GSA method for `./data/PRISMA/Test/Reduced_Resolution/PRS_L2D_STD_20220905101901_20220905101905_0001_CAGLIARI_RR.mat`.

https://github.com/matciotola/hyperspectral_pansharpening_toolbox/blob/8561bcd06fceb1482c80e5face5b10acbfdc2d20/Utils/pansharpening_aux_tools.py#L9

`RuntimeError: torch.linalg.lstsq: input.size(-2) should match other.size(-2)` occurs in the line above.

An error appears for nearly all methods during RR evaluation, not only for GSA, but also for EXP, BT-H, etc. I suspect that it is the input data for RR evaluation that causes the error, rather than the GSA method.

I print out the shape some variables that may be useful in `exp_input`.
`ms_lr.shape = torch.Size([1, 159, 132, 169])`
`ms.shape = torch.Size([1, 159, 792, 1164])`
`pan.shape = torch.Size([1, 1, 796, 1166])`

It seems that `ms` and `pan` has shape mismatch. Maybe there is something wrong in the script `elaborate_PRISMA_images.py`?

**Comment by matciotola** [comment]
It should. Let me check. I will come back Monday with news! :) 
Sorry about that

**Comment by matciotola** [comment]
Dear @shwangtangjun,
Thank you for highlighting the problem. 
I have analyzed all the code and fixed the bug.
Now the code should work perfectly. 
Sorry about the inconvenience.
Please, let me know if everything is fine now. The problem was only on the RR test patches, the FR analysis you made is still valid.
Thank you for your support,
Matteo

**Comment by shwangtangjun** [comment]
Thanks for your effort! I have tried again and everything works fine now.
